language: csharp
dist: trusty
dotnet: 2.1.300
mono: none
solution: "./Flora.sln"
install:
  - dotnet restore Flora.sln
script:
  - dotnet build
  - dotnet test Flora.Tests/Flora.Tests.csproj
  - dotnet test Flora.IntegrationTests/Flora.IntegrationTests.csproj